### ISSUE TITLE
パスワード変更API追加

### ISSUE THREAD

**Issue by zhenbin-z** [poposuke1995x/muscle-training-manager-api#14]
@poposuke1995x 
お疲れ様です。Splinkの張です。
表記のAPI一個を追加して、PRを提出していただくことが可能でしょうか？
エンドポイントは任せます。
不明点があれば、このissuesで議論しても大丈夫です。

要件：
- firebaseベース経由してパスワード変更する

**Comment by zhenbin-z** [comment]
@poposuke1995x すみません、記載漏れがありました。
上記のAPIに対して、テストケースの作成もお願いします。

**Comment by poposuke1995x** [comment]
@zhenbin-z 

お世話になっております。

パスワード変更APIを追加しました。
以下、プルリクエストのURLです。

https://github.com/poposuke1995x/muscle-training-manager-api/pull/16

アーキテクチャ説明の要約はREADME.mdに記載しております。

パスワード変更の機能はすでにデプロイしていますので、画面側からも確認していただけます。
また、動的ルーティングによって表示しているページにおいて、再読み込みが走ると404エラーが発生するバグがありましたが、修正してあわせてデプロイしました。

以上、よろしくお願いいたします。
